# Generated by Django 5.0 on 2023-12-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deepfake",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("Модель ResNet101", "Модель ResNet101"),
                            ("Модель InceptionV3", "Модель InceptionV3"),
                            ("Модель InceptionResNetV2", "Модель InceptionResNetV2"),
                        ],
                        default="Модель ResNet101",
                        max_length=30,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("FAKE", "FAKE"), ("NOT FAKE", "NOT FAKE")],
                        default="FAKE",
                        max_length=10,
                    ),
                ),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                ("video", models.FileField(upload_to="")),
            ],
            options={
                "db_table": "deepfake",
            },
        ),
    ]
